language: python
python:
  - "3.6"

services:
  - postgresql

before script:
  - psql -c "create database pantry_dev_test;" -U postgres

env:
  - TEST_DATABASE_URL='postgres://localhost:5432/pantry_dev'

install:
  - pip install -e .[testing]

script:
  - pytest

notifications:
    email: true
    